services:
  - type: web
    name: ekhum
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: EVOLUTION_GO_API_URL
        value: http://localhost:8080
      - key: SERVER_PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: AWS_REGION
        value: ap-south-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_SES_FROM_EMAIL
        sync: false
